"""empty message

Revision ID: c2da0ede981b
Revises: 
Create Date: 2020-04-18 16:32:22.250383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2da0ede981b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('test',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('test', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('player',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('favorite_game', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_game'], ['game._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    op.drop_table('test')
    op.drop_table('game')
    # ### end Alembic commands ###
